version: '3'
services:
  vite-app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_GEMINI_API_KEY=AIzaSyARjSnCy6jajQJzW3U7wIvxAiV8Ft5Kb-c
